build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: false

formatting:
  active: true
  autoCorrect: true
  ChainWrapping:
    active: true
    autoCorrect: true
  CommentSpacing:
    active: true
    autoCorrect: true
  Indentation:
    active: false
  ModifierOrdering:
    active: true
    autoCorrect: true
  NoConsecutiveBlankLines:
    active: true
    autoCorrect: true
  NoEmptyClassBody:
    active: true
    autoCorrect: true
  NoLineBreakAfterElse:
    active: true
    autoCorrect: true
  NoLineBreakBeforeAssignment:
    active: true
    autoCorrect: true
  NoMultipleSpaces:
    active: true
    autoCorrect: true
  NoSemicolons:
    active: true
    autoCorrect: true
  NoTrailingSpaces:
    active: true
    autoCorrect: true
  NoUnitReturn:
    active: true
    autoCorrect: true
  NoUnusedImports:
    active: true
    autoCorrect: true
  NoWildcardImports:
    active: true
  MaximumLineLength:
    active: false
    excludes: ['**Test**']
  PackageName:
    active: false
  ParameterListWrapping:
    active: true
    autoCorrect: true
    maxLineLength: 125
  SpacingAroundColon:
    active: true
    autoCorrect: true
  SpacingAroundComma:
    active: true
    autoCorrect: true
  SpacingAroundCurly:
    active: true
    autoCorrect: true
  SpacingAroundDot:
    active: true
    autoCorrect: true
  SpacingAroundKeyword:
    active: true
    autoCorrect: true
  SpacingAroundOperators:
    active: true
    autoCorrect: true
  StringTemplate:
    active: true
    autoCorrect: true
  FinalNewline:
    active: false

naming:
  TopLevelPropertyNaming:
    active: true
    constantPattern: '[A-Z][_A-Z0-9a-z]*'
    propertyPattern: '[A-Za-z][_A-Za-z0-9]*'
    privatePropertyPattern: '_?[A-Za-z][_A-Za-z0-9]*'
  PackageNaming:
    active: false
  FunctionNaming:
    active: false

exceptions:
  active: false

style:
  BracesOnIfStatements:
    active: false
  BracesOnWhenStatements:
    active: false
  MaxLineLength:
    maxLineLength: 125
    excludeCommentStatements: true
  NewLineAtEndOfFile:
    active: false
